name: Flutter Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Build
        run: |
          # Sabse pehle pubspec.yaml dhundho aur wahan jao
          PROJECT_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \;)
          cd "$PROJECT_DIR"
          
          # Android setup
          flutter pub get
          flutter build apk --release
          
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: LeoVox-APK
          path: '**/build/app/outputs/flutter-apk/app-release.apk'
          
